name: flutter_project_template_riverpod
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #* UI
  cached_network_image: ^3.2.2
  flash: ^2.0.5
  flutter_keyboard_visibility: ^5.4.0
  google_fonts: ^3.0.1

  #* Icons
  flutter_vector_icons: ^2.0.0

  #* Firebase
  firebase_analytics: ^10.0.3
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3
  firebase_messaging: ^14.0.3

  #* Local notification
  awesome_notifications: ^0.7.4+1

  #* Network
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1

  #* Dart data class
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  #* State management
  hooks_riverpod: ^2.1.0

  #* Logging
  logging: ^1.1.0

  #* Routing
  go_router: ^5.1.1

  #* Persistent storage
  flutter_secure_storage: ^6.0.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  #* Localization
  intl: ^0.17.0

  #* Date Time util
  jiffy: ^5.0.0

  #* Misc
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #* Code generators
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.13
  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
